import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Professional PDF Report Generator for Smart Campus Hub
 * @param {Object} user - The current user object (name, role, etc)
 * @param {Object} data - The dataset to include in the report
 * @param {string} type - The type of report ('ADMIN_AUDIT', 'TECH_PERFORMANCE', 'USER_ACTIVITY')
 */
export const generateReport = (user, data, type) => {
    try {
        console.log(`Generating ${type} report for ${user?.name}...`);
        
        if (!user || !user.role) {
            throw new Error("Invalid user context for report generation.");
        }

        const doc = new jsPDF();
        const timestamp = new Date().toLocaleString();
        const primaryColor = [59, 130, 246]; // #3b82f6

        // --- Header Section ---
        doc.setFillColor(...primaryColor);
        doc.rect(0, 0, 210, 40, 'F');
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text('Smart Campus Operations Hub', 15, 20);
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Official System Report • Generated on ${timestamp}`, 15, 30);

        // --- Meta Info ---
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Report Details', 15, 55);
        
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.text(`Subject: ${type.replace(/_/g, ' ')}`, 15, 62);
        const roleLabel = user.role.startsWith('ROLE_') ? user.role.replace('ROLE_', '') : user.role;
        doc.text(`Generated By: ${user.name} (${roleLabel})`, 15, 68);
        doc.text(`Status: Official Document`, 15, 74);

        let currentY = 90;

        // --- Admin Audit Report ---
        if (type === 'ADMIN_AUDIT') {
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('System Summary', 15, currentY);
            
            const statsData = [
                ['Category', 'Count'],
                ['Total Registered Users', data.users?.length || 0],
                ['Active Campus Resources', data.resources?.length || 0],
                ['Total Booking Requests', data.bookings?.length || 0],
                ['Active Incident Tickets', data.tickets?.filter(t => t.status !== 'RESOLVED').length || 0],
            ];

            autoTable(doc, {
                startY: currentY + 5,
                head: [statsData[0]],
                body: statsData.slice(1),
                theme: 'striped',
                headStyles: { fillColor: primaryColor }
            });

            currentY = doc.lastAutoTable.finalY + 15;

            if (data.resources?.length > 0) {
                doc.text('Campus Resources Inventory', 15, currentY);
                autoTable(doc, {
                    startY: currentY + 5,
                    head: [['ID', 'Name', 'Type', 'Location', 'Status']],
                    body: data.resources.map(r => [r.id, r.name, r.type, r.location, r.status]),
                    theme: 'grid',
                    headStyles: { fillColor: primaryColor }
                });
                currentY = doc.lastAutoTable.finalY + 15;
            }

            if (data.tickets?.length > 0) {
                if (currentY > 240) { doc.addPage(); currentY = 20; }
                doc.text('Global Incident Log (Recent)', 15, currentY);
                autoTable(doc, {
                    startY: currentY + 5,
                    head: [['ID', 'Subject', 'Priority', 'Status', 'Creator']],
                    body: data.tickets.slice(-15).reverse().map(t => [t.id, t.category, t.priority, t.status, t.creatorId]),
                    theme: 'striped',
                    headStyles: { fillColor: [239, 68, 68] }
                });
            }
        }

        // --- Technician Performance Report ---
        if (type === 'TECH_PERFORMANCE') {
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('Job Queue Summary', 15, currentY);

            const activeTickets = data.tickets?.filter(t => t.status !== 'RESOLVED') || [];
            const resolvedTickets = data.tickets?.filter(t => t.status === 'RESOLVED') || [];

            const techStats = [
                ['Metric', 'Value'],
                ['Tickets Assigned to You', data.tickets?.length || 0],
                ['Currently In-Progress/Open', activeTickets.length],
                ['Total Resolved by You', resolvedTickets.length],
            ];

            autoTable(doc, {
                startY: currentY + 5,
                head: [techStats[0]],
                body: techStats.slice(1),
                theme: 'striped',
                headStyles: { fillColor: [139, 92, 246] }
            });

            currentY = doc.lastAutoTable.finalY + 15;

            if (data.tickets?.length > 0) {
                doc.text('Detailed Task List', 15, currentY);
                autoTable(doc, {
                    startY: currentY + 5,
                    head: [['ID', 'Incident', 'Priority', 'Current Status', 'Reported On']],
                    body: data.tickets.map(t => [
                        t.id, 
                        t.category?.replace('_', ' '), 
                        t.priority, 
                        t.status, 
                        new Date(t.createdAt).toLocaleDateString()
                    ]),
                    theme: 'grid',
                    headStyles: { fillColor: [139, 92, 246] }
                });
            }
        }

        // --- User Activity Report ---
        if (type === 'USER_ACTIVITY') {
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('My Campus Activity Overview', 15, currentY);

            const summary = [
                ['Activity Type', 'Total Records'],
                ['Facility Bookings', data.bookings?.length || 0],
                ['Incidents Reported', data.tickets?.length || 0],
            ];

            autoTable(doc, {
                startY: currentY + 5,
                head: [summary[0]],
                body: summary.slice(1),
                theme: 'striped',
                headStyles: { fillColor: primaryColor }
            });

            currentY = doc.lastAutoTable.finalY + 15;

            if (data.bookings?.length > 0) {
                doc.text('My Booking History', 15, currentY);
                autoTable(doc, {
                    startY: currentY + 5,
                    head: [['Facility', 'Start Time', 'Status']],
                    body: data.bookings.map(b => [
                        b.resource?.name, 
                        new Date(b.startTime).toLocaleString(), 
                        b.status
                    ]),
                    theme: 'grid',
                    headStyles: { fillColor: primaryColor }
                });
                currentY = doc.lastAutoTable.finalY + 15;
            }

            if (data.tickets?.length > 0) {
                if (currentY > 240) { doc.addPage(); currentY = 20; }
                doc.text('My Reported Incidents', 15, currentY);
                autoTable(doc, {
                    startY: currentY + 5,
                    head: [['ID', 'Subject', 'Status', 'Date Reported']],
                    body: data.tickets.map(t => [
                        t.id, 
                        t.category?.replace('_', ' '), 
                        t.status, 
                        new Date(t.createdAt).toLocaleDateString()
                    ]),
                    theme: 'striped',
                    headStyles: { fillColor: [239, 68, 68] }
                });
            }
        }

        // --- Footer Section ---
        const pageCount = doc.internal.getNumberOfPages();
        for(let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Page ${i} of ${pageCount} • Smart Campus Operations Hub • Confidential`, 105, 285, { align: 'center' });
        }

        // --- Save the PDF ---
        const fileName = `${type}_${new Date().toISOString().split('T')[0]}.pdf`;
        doc.save(fileName);
        console.log("PDF generated successfully.");

    } catch (error) {
        console.error("Failed to generate PDF report:", error);
        alert("Sorry, there was an error generating your report. Please try again later.");
    }
};
